import type { Metadata } from 'next'
import { Figtree, Roboto } from 'next/font/google'
import './globals.css'
import { Header } from './components/Header'

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['700', '400'],
  variable: '--font-roboto',
})

const figtree = Figtree({
  subsets: ['latin'],
  weight: ['700', '300'],
  variable: '--font-figtree',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className={`${roboto.variable} ${figtree.variable}`}>
      <body>
        <div className="min-h-screen overflow-hidden">
          <Header />
          <main className="max-w-[100vw]">{children}</main>
        </div>
      </body>
    </html>
  )
}
